---

- name: Install Debian | Add td-agent-bit apt-key
  apt_key:
    url: https://packages.fluentbit.io/fluentbit.key
    state: present

- name: Install Debian | Add td-agent-bit repository
  apt_repository:
    repo: 'deb https://packages.fluentbit.io/ubuntu/bionic bionic main'
    state: present
    filename: td-agent-bit
    update_cache: true
